services:
  portfolio:
    container_name: portfolio
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    build:
      context: .
      dockerfile: prod.Dockerfile
    restart: always
    ports:
      - 8000:3000
