services:
  next-app:
    container_name: next-app
    build:
      context: .
      dockerfile: prod.Dockerfile
      args:
        TO_EMAIL: ${TO_EMAIL}
        RESEND_API_KEY: ${RESEND_API_KEY}
    restart: always
    ports:
      - 8000:3000
